In [13]:
import pandas as pd
import numpy as np

In [14]:
df=pd.read_csv("train.csv")

In [15]:
df

      id  gravity    ph  osmo  cond  urea  calc  target
0      0    1.013  6.19   443  14.8   124  1.45       0
1      1    1.025  5.40   703  23.6   394  4.18       0
2      2    1.009  6.13   371  24.5   159  9.04       0
3      3    1.021  4.91   442  20.8   398  6.63       1
4      4    1.021  5.53   874  17.8   385  2.21       1
..   ...      ...   ...   ...   ...   ...   ...     ...
409  409    1.011  5.21   527  21.4    75  1.53       0
410  410    1.024  5.53   577  19.7   224  0.77       0
411  411    1.018  6.28   455  22.2   270  7.68       1
412  412    1.008  7.12   325  12.6    75  1.03       1
413  413    1.011  6.13   364   9.9   159  0.27       0

[414 rows x 8 columns]

In [16]:
cols=['gravity','ph','osmo','cond','urea','calc']
for i in cols:
    df[i]=(df[i]-np.mean(df[i]))/np.std(df[i])

In [17]:
df

      id   gravity        ph      osmo      cond      urea      calc  target
0      0 -0.734032  0.365623 -0.889728 -0.884388 -1.134869 -0.829136       0
1      1  1.065904 -0.865897  0.219521  0.288059  0.846384  0.020338       0
2      2 -1.334010  0.272090 -1.196904  0.407969 -0.878040  1.532589       0
3      3  0.465925 -1.629751 -0.893994 -0.084992  0.875736  0.782687       1
4      4  0.465925 -0.663242  0.949065 -0.484690  0.780342 -0.592652       1
..   ...       ...       ...       ...       ...       ...       ...     ...
409  409 -1.034021 -1.162085 -0.531355 -0.005053 -1.494430 -0.804243       0
410  410  0.915909 -0.663242 -0.318038 -0.231548 -0.401072 -1.040727       0
411  411  0.015941  0.505922 -0.838532  0.101534 -0.063525  1.109408       1
412  412 -1.484005  1.815386 -1.393156 -1.177500 -1.494430 -0.959824       1
413  413 -1.034021  0.272090 -1.226768 -1.537228 -0.878040 -1.196308       0

[414 rows x 8 columns]

In [18]:
#training and testing
X=df.drop(['id','target'],axis=1)
Y=df['target']

In [19]:
X

      gravity        ph      osmo      cond      urea      calc
0   -0.734032  0.365623 -0.889728 -0.884388 -1.134869 -0.829136
1    1.065904 -0.865897  0.219521  0.288059  0.846384  0.020338
2   -1.334010  0.272090 -1.196904  0.407969 -0.878040  1.532589
3    0.465925 -1.629751 -0.893994 -0.084992  0.875736  0.782687
4    0.465925 -0.663242  0.949065 -0.484690  0.780342 -0.592652
..        ...       ...       ...       ...       ...       ...
409 -1.034021 -1.162085 -0.531355 -0.005053 -1.494430 -0.804243
410  0.915909 -0.663242 -0.318038 -0.231548 -0.401072 -1.040727
411  0.015941  0.505922 -0.838532  0.101534 -0.063525  1.109408
412 -1.484005  1.815386 -1.393156 -1.177500 -1.494430 -0.959824
413 -1.034021  0.272090 -1.226768 -1.537228 -0.878040 -1.196308

[414 rows x 6 columns]

In [20]:
Y

0      0
1      0
2      0
3      1
4      1
      ..
409    0
410    0
411    1
412    1
413    0
Name: target, Length: 414, dtype: int64

In [75]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,Y,train_size=0.80)

In [76]:
from sklearn.tree import DecisionTreeClassifier
from time import time

#Training time
start=time()

t=DecisionTreeClassifier(criterion='gini',max_depth=3)
model=t.fit(x_train,y_train)
end=time()

In [77]:
#Criteria metrics for training
from sklearn.metrics import precision_score,recall_score,f1_score,confusion_matrix

ypred=model.predict(x_train)
missclass_rate=((y_train!=ypred).sum()/y_train.shape[0])*100
precision=precision_score(y_train,ypred)
recall=recall_score(y_train,ypred)
f1=f1_score(y_train,ypred)
c=confusion_matrix(y_train,ypred)
sensitivity=c[0][0]/(c[0][0]+c[1][0])
specificity=c[1][1]/(c[1][1]+c[0][1])
accuracy=model.score(x_train,y_train)

In [78]:
#print train metrics
print("Time : ",end-start)
print(missclass_rate)
print(precision)
print(recall)
print(f1)
print(sensitivity)
print(specificity)
print(accuracy)

Time :  0.004008054733276367
23.564954682779458
0.712707182320442
0.832258064516129
0.7678571428571428
0.8266666666666667
0.712707182320442
0.7643504531722054

In [79]:
#On testing
ypred=model.predict(x_test)
missclass_rate=((y_test!=ypred).sum()/y_test.shape[0])*100
precision=precision_score(y_test,ypred)
recall=recall_score(y_test,ypred)
f1=f1_score(y_test,ypred)
c=confusion_matrix(y_test,ypred)
sensitivity=c[0][0]/(c[0][0]+c[1][0])
specificity=c[1][1]/(c[1][1]+c[0][1])
accuracy=t.score(x_test,y_test)

In [80]:
#print test metrics
print(missclass_rate)
print(precision)
print(recall)
print(f1)
print(sensitivity)
print(specificity)
print(accuracy)

32.53012048192771
0.5227272727272727
0.7931034482758621
0.6301369863013699
0.8461538461538461
0.5227272727272727
0.6746987951807228